sources:
  obsidian-skills:
    whitelist: []
    blacklist: 
      - json-canvas

  axton-obsidian-visual-skills:
    whitelist: []
    blacklist: []

  khazix-skills:
    whitelist: []
    blacklist: []
